spring.application.name=bus-backend
spring.data.mongodb.uri=mongodb+srv://chathunipathirana2002_db_user:vc7xYYA9DENYdeoX@cluster0.tzqkm3r.mongodb.net/HighwayBusManagement?appName=Cluster0
server.port=8084
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
